version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - gis_2_network
    volumes:
      - gis_2_static:/data/static/
      - gis_2_media:/data/media/
      - gis_log:/var/log/nginx/
      - /home/kms01041202735/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - mode: host
      protocol: tcp
      target: 80
      published: 80

  goaccess:
    image: allinurl/goaccess:1.5.1
    ports:
      - 7890:7890
    volumes:
      - gis_log:/var/log/nginx/
    command: /var/log/nginx/gis_access.log -o /var/log/nginx/report.html --log-format=COMBINED --real-time-html

  django:
    image: gis_2_django:5
    networks:
      - gis_2_network
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD
    volumes:
      - gis_2_static:/home/gis_1ban_2/staticfiles/
      - gis_2_media:/home/gis_1ban_2/media/

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_2_network
    volumes:
      - gis_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_DATABASE: gyul
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD

networks:
  gis_2_network:

volumes:
  gis_2_static:
  gis_2_media:
  gis_mariadb:
  gis_log:

secrets:
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  DJANGO_SECRET_KEY:
    external: true