version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - gis_2_network
    volumes:
      - gis_2_static:/data/static/
      - gis_2_media:/data/media/
      - /home/kms01041202735/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80

  django:
    image: gis_2_django:3
    networks:
      - gis_2_network
    volumes:
      - gis_2_static:/home/gis_1ban_2/staticfiles/
      - gis_2_media:/home/gis_1ban_2/media/

networks:
  gis_2_network:

volumes:
  gis_2_static:
  gis_2_media: